version: '3.4'

services:
  stravakomootsync:
    image: stravakomootsync
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: stravakomootsync
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./token.json:/token.json
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 10m
